name: test_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # version 2.10.2

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  chopper: ^4.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
